-- ARCHIVO DE CONFIGURACIÓN DE BASE DE DATOS (SUPABASE SQL EDITOR)

-- 1. TABLA DE DEPARTAMENTOS
CREATE TABLE departamentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. TABLA DE EQUIPOS
CREATE TABLE equipos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. TABLA DE TICKETS
CREATE TABLE tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero SERIAL NOT NULL UNIQUE, 
    asunto TEXT NOT NULL,
    descripcion TEXT,
    peticionario_nombre TEXT NOT NULL,
    peticionario_email TEXT NOT NULL,
    estado TEXT DEFAULT 'Abierto' CHECK (estado IN ('Abierto', 'Cerrado', 'En Proceso')),
    prioridad TEXT DEFAULT 'Normal' CHECK (prioridad IN ('Baja', 'Normal', 'Alta', 'Emergencia')),
    departamento_id BIGINT REFERENCES departamentos(id) ON DELETE SET NULL,
    equipo_id BIGINT REFERENCES equipos(id) ON DELETE SET NULL,
    asignado_a UUID REFERENCES auth.users(id) ON DELETE SET NULL, 
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    fecha_vencimiento TIMESTAMP WITH TIME ZONE
);

-- Insertar datos iniciales de ejemplo para los Departamentos y Filtros
INSERT INTO departamentos (nombre) VALUES 
('Soporte Mantenimiento y Sistemas'), 
('Atención al Cliente'), 
('Administración y Facturación');

INSERT INTO equipos (nombre) VALUES 
('Equipo de Guardia Nivel 1'), 
('Soporte de Infraestructura');
